import type { Prisma } from '@/lib/prisma';
import { prisma } from '@/lib/prisma';

async function getCurrentData() {
  const [rawMonsterSizes, rawMonsterTypes, rawMonsterSubTypes, rawMinis] =
    await Promise.all([
      prisma.monsterSize.findMany(),
      prisma.monsterType.findMany(),
      prisma.monsterSubType.findMany(),
      prisma.mini.findMany(),
    ]);

  return {
    monsterSizes: Object.fromEntries(
      rawMonsterSizes.map((entry) => [entry.name, entry.id]),
    ),
    monsterTypes: Object.fromEntries(
      rawMonsterTypes.map((entry) => [entry.name, entry.id]),
    ),
    monsterSubTypes: Object.fromEntries(
      rawMonsterSubTypes.map((entry) => [entry.name, entry.id]),
    ),
    minis: Object.fromEntries(rawMinis.map((entry) => [entry.name, entry.id])),
  };
}

const SEED_DATA = [
  {
    name: 'Aboleth',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Aberration',
  },
  {
    name: 'Animated Armor',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Construct',
  },
  {
    name: 'Ankheg',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Barbed Devil',
    quantity: 2,
    size: 'Medium',
    subtype: 'Devil',
    type: 'Fiend',
  },
  {
    name: 'Basilisk',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Bat (Giant)',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Beast',
  },
  {
    name: 'Bearded Devil',
    quantity: 2,
    size: 'Medium',
    subtype: 'Devil',
    type: 'Fiend',
  },
  {
    name: 'Beholder',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Aberration',
  },
  {
    name: 'Black Pudding',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Ooze',
  },
  {
    name: 'Bone Devil',
    quantity: 1,
    size: 'Large',
    subtype: 'Devil',
    type: 'Fiend',
  },
  {
    name: 'Bugbear',
    quantity: 4,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Bulette',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Cambion',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Fiend',
  },
  {
    name: 'Carrion Crawler',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Chain Devil',
    quantity: 1,
    size: 'Medium',
    subtype: 'Devil',
    type: 'Fiend',
  },
  {
    name: 'Chimera',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Chuul',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Aberration',
  },
  {
    name: 'Cockatrice',
    quantity: 1,
    size: 'Small',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Corgi',
    quantity: 1,
    size: 'Small',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Couatl',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Celestial',
  },
  {
    name: 'Demilich',
    quantity: 1,
    size: 'Tiny',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Demon Orc',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Displacer Beast',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Djinni',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Elemental',
  },
  {
    name: 'Doppleganger',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Dragon (Black)',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Dragon',
  },
  {
    name: 'Dragon (Blue)',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Dragon',
  },
  {
    name: 'Dragon (Bronze)',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Dragon',
  },
  {
    name: 'Dragon (Gold)',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Dragon',
  },
  {
    name: 'Dragon (Green)',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Dragon',
  },
  {
    name: 'Dragon (Red)',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Dragon',
  },
  {
    name: 'Dragon (Silver)',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Dragon',
  },
  {
    name: 'Dragon (White)',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Dragon',
  },
  {
    name: 'Dragonborn',
    quantity: 25,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Duergar',
    quantity: 3,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Dwarf',
    quantity: 24,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Elf',
    quantity: 24,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Erinyes',
    quantity: 1,
    size: 'Medium',
    subtype: 'Devil',
    type: 'Fiend',
  },
  {
    name: 'Ettercap',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Ettin',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Giant',
  },
  {
    name: 'Flame Skull',
    quantity: 1,
    size: 'Tiny',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Gargoyle',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Elemental',
  },
  {
    name: 'Gelatinous Cube',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Ooze',
  },
  {
    name: 'Ghost',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Ghoul',
    quantity: 8,
    size: 'Medium',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Giant (Storm)',
    quantity: 1,
    size: 'Huge',
    subtype: null,
    type: 'Giant',
  },
  {
    name: 'Giff',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Girallon',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Gnoll',
    quantity: 4,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Gnome',
    quantity: 24,
    size: 'Small',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Goblin',
    quantity: 10,
    size: 'Large',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Golem (Iron)',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Construct',
  },
  {
    name: 'Golem (Silver)',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Construct',
  },
  {
    name: 'Golem (Stone)',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Construct',
  },
  {
    name: 'Gorgon',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Grell',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Aberration',
  },
  {
    name: 'Grick',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Griffon',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Grimlock',
    quantity: 2,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Grung',
    quantity: 1,
    size: 'Small',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Guard',
    quantity: 11,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Hag (Night)',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Fiend',
  },
  {
    name: 'Half-Elf',
    quantity: 24,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Half-Orc',
    quantity: 24,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Halfling',
    quantity: 24,
    size: 'Small',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Harpy',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Hell Hound',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Fiend',
  },
  {
    name: 'Hobgoblin',
    quantity: 4,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Hook Horror',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Horned Devil',
    quantity: 1,
    size: 'Large',
    subtype: 'Devil',
    type: 'Fiend',
  },
  {
    name: 'Human',
    quantity: 24,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Hydra',
    quantity: 1,
    size: 'Huge',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Imp',
    quantity: 3,
    size: 'Tiny',
    subtype: 'Devil',
    type: 'Fiend',
  },
  {
    name: 'Intellect Devourer',
    quantity: 2,
    size: 'Tiny',
    subtype: null,
    type: 'Aberration',
  },
  {
    name: 'Kitsune',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Kobold',
    quantity: 12,
    size: 'Small',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Kuo-Toa',
    quantity: 2,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Lemure',
    quantity: 2,
    size: 'Medium',
    subtype: 'Devil',
    type: 'Fiend',
  },
  {
    name: 'Lich',
    quantity: 2,
    size: 'Medium',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Manticore',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Medusa',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Merfolk',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Mimic',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Mind Flayer',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Aberration',
  },
  {
    name: 'Minotaur',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Mummy',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Myconid',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Plant',
  },
  {
    name: 'Naga',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Nightmare',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Fiend',
  },
  {
    name: 'Ogre',
    quantity: 3,
    size: 'Large',
    subtype: null,
    type: 'Giant',
  },
  {
    name: 'Ooze (Grey)',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Ooze',
  },
  {
    name: 'Orc',
    quantity: 12,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Otyugh',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Aberration',
  },
  {
    name: 'Owlbear',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Pegasus',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Celestial',
  },
  {
    name: 'Pit Fiend',
    quantity: 1,
    size: 'Large',
    subtype: 'Devil',
    type: 'Fiend',
  },
  {
    name: 'Pit Fiend',
    quantity: 1,
    size: 'Large',
    subtype: 'Devil',
    type: 'Fiend',
  },
  {
    name: 'Pixie',
    quantity: 1,
    size: 'Tiny',
    subtype: null,
    type: 'Fey',
  },
  {
    name: 'Purple Worm',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Rakshasa',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Fiend',
  },
  {
    name: 'Roper',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Rust Monster',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Shadow',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Shambling Mound',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Plant',
  },
  {
    name: 'Shark Pirate',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Skeleton',
    quantity: 12,
    size: 'Medium',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Slaad',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Aberration',
  },
  {
    name: 'Specter',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Sphinx',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Succubus',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Fiend',
  },
  {
    name: 'Tarrasque',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Thri-kreen',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Tiamat',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Fiend',
  },
  {
    name: 'Tiefling',
    quantity: 24,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Tortle',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Troll',
    quantity: 4,
    size: 'Large',
    subtype: null,
    type: 'Giant',
  },
  {
    name: 'Ultroloth',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Fiend',
  },
  {
    name: 'Umber Hulk',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Vampire',
    quantity: 2,
    size: 'Medium',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Vine Blight',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Plant',
  },
  {
    name: 'Walking Statue',
    quantity: 1,
    size: 'Gargantuan',
    subtype: null,
    type: 'Construct',
  },
  {
    name: 'Werewolf',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Will-o-Wisp',
    quantity: 1,
    size: 'Tiny',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Witch',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Humanoid',
  },
  {
    name: 'Wraith',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Undead',
  },
  {
    name: 'Wyvern',
    quantity: 1,
    size: 'Large',
    subtype: null,
    type: 'Dragon',
  },
  {
    name: 'Xorn',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Elemental',
  },
  {
    name: 'Yuan-Ti',
    quantity: 1,
    size: 'Medium',
    subtype: null,
    type: 'Monstrosity',
  },
  {
    name: 'Zombie',
    quantity: 5,
    size: 'Medium',
    subtype: null,
    type: 'Undead',
  },
];

async function main() {
  const { monsterSizes, monsterTypes, monsterSubTypes, minis } =
    await getCurrentData();

  for (const row of SEED_DATA) {
    const data: Prisma.MiniUncheckedCreateInput = {
      name: row.name,
      sizeId: monsterSizes[row.size],
      typeId: monsterTypes[row.type],
      subTypeId: row.subtype ? monsterSubTypes[row.subtype] : null,
    };
    await prisma.mini.upsert({
      where: { id: minis[row.name] ?? -1 },
      create: data,
      update: data,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  // eslint-disable-next-line unicorn/prefer-top-level-await -- tsx compiles to CJS which doesn't support TLA
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    // eslint-disable-next-line unicorn/no-process-exit
    process.exit(1);
  });
